apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  name: github-secret
type: kubernetes.io/basic-auth
data:
  password: cGVyc29uYWxhY2Nlc3N0b2tlbgo=
  username: dXNlcm5hbWUK