apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: quay.io
  name: quay-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoidXNlcm5hbWUiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RPSJ9fX0=
type: kubernetes.io/dockerconfigjson
